export const FEATURE_RATING_CSAT_PAYMENT = 'RATING_CSAT_PAYMENT';
export const FEATURE_EDIT_BILLING_PAGE = 'EDIT_BILLING_PAGE';

export const FEATURE_KUSHKI_CREDIT_CARD = 'KUSHKI_CREDIT_CARD';
export const FEATURE_KUSHKI_TRANSFER_IN = 'KUSHKI_TRANSFER_IN';
export const FEATURE_KUSHKI_CASH_IN = 'KUSHKI_CASH_IN';

export const FEATURE_VERIFY_RFC = 'VERIFY_RFC';
