const QUERY_KEY_CONCEPTS = 'concept';
const QUERY_KEY_SCHOLARSHIPS = 'scholarships';
const QUERY_KEY_DUE_ORDERS_STUDENT = 'dueOrdersOfStudent';
const JOYRIDE_KEY = 'joyride';

export { QUERY_KEY_CONCEPTS, QUERY_KEY_DUE_ORDERS_STUDENT, QUERY_KEY_SCHOLARSHIPS, JOYRIDE_KEY };
