const QUERY_KEY_CONCEPTS = 'concept';
const QUERY_KEY_SCHOLARSHIPS = 'scholarships';
const QUERY_KEY_SCHOLARSHIPS_OLD = 'scholarships_old';
const QUERY_KEY_ASSIGNMENTS = 'assignments';
const QUERY_KEY_DUE_ORDERS_STUDENT = 'dueOrdersOfStudent';
const QUERY_KEY_ORDERS_FOR_PAY_DETAIL = 'order_for_pay_detail';
const QUERY_KEY_STUDENT_DETAIL = 'studentDetail';
const JOYRIDE_KEY = 'joyride';

export {
  QUERY_KEY_ASSIGNMENTS,
  QUERY_KEY_CONCEPTS,
  QUERY_KEY_DUE_ORDERS_STUDENT,
  QUERY_KEY_ORDERS_FOR_PAY_DETAIL,
  QUERY_KEY_STUDENT_DETAIL,
  QUERY_KEY_SCHOLARSHIPS,
  QUERY_KEY_SCHOLARSHIPS_OLD,
  JOYRIDE_KEY,
};
