import { Locator, Page } from '@playwright/test';

export class StudentsPage {
  readonly page: Page;
  readonly studentsTxt: Locator;
  readonly totalStudentsTxt: Locator;
  readonly totalWithoutDebtStudentsTxt: Locator;
  readonly totalWithDebtStudentsTxt: Locator;
  readonly highDelinquencyTxt: Locator;
  readonly highDelinquencyHelperTxt: Locator;
  readonly mediumDelinquencyTxt: Locator;
  readonly mediumDelinquencyHelperTxt: Locator;
  readonly lowDelinquencyTxt: Locator;
  readonly lowDelinquencyHelperTxt: Locator;
  readonly studentsListTxt: Locator;
  readonly newStudentBtn: Locator;
  readonly studenRowNameTxt: Locator;
  readonly guardinFilterTxtBox: Locator;
  readonly studentFilterTxtBox: Locator;
  readonly downloadArrowBtn: Locator;
  readonly goToPageTxtLabel: Locator;
  readonly spinButtonBox: Locator;
  readonly navigateOnePageBtn: Locator;
  readonly xOfx: Locator;
  readonly navigateLastPageBtn: Locator;
  readonly lastPageCount: Locator;
  readonly navigateFirstPageBtn: Locator;
  readonly firstPageCount: Locator;
  readonly studentLevel: Locator;
  readonly levelFilterSelector: Locator;
  readonly optionSecundaria: Locator;
  readonly optionPrimaria: Locator;
  readonly optionPreescolar: Locator;
  readonly rowLevelPreescolar: Locator;
  readonly rowLevelSecundaria: Locator;
  readonly rowLevelPrimaria: Locator;
  readonly optionSecciónPrimariaA: Locator;
  readonly rowSeccionPrimariaA: Locator;
  readonly sectionFilterSelector: Locator;
  readonly colegiturasVencidasFilterSelector: Locator;
  readonly optionCV1: Locator;
  readonly optionCV2: Locator;
  readonly optionCV3: Locator;
  readonly tutorFilterTxt: Locator;
  readonly optionFilteredByTutor: Locator;
  readonly studentFilterTxt: Locator;
  readonly optionFilteredByStudent: Locator;
  readonly filterBtn: Locator;
  readonly applyFilterBtn: Locator;
  readonly cleanAllFiltersBtn: Locator;
  readonly highDelinquencyStudensCounterTxt: Locator;
  readonly schoollarshipCicle: Locator;
  readonly delinquencyStatics: Locator;
  readonly studentFirstName: Locator;
  readonly studentCurp: Locator;
  readonly studentBirthdate: Locator;
  readonly studentLastName: Locator;
  readonly genderM: Locator;
  readonly nextBtn: Locator;
  readonly enrollmentCode: Locator;
  readonly levelDD: Locator;
  readonly gradeBtn: Locator;
  readonly groupBtn: Locator;
  readonly findExistingGuardianChk: Locator;
  readonly registerNewGuardianChk: Locator;
  readonly guardianFirstName: Locator;
  readonly guardianLastName: Locator;
  readonly guardianEmail: Locator;
  readonly guardianCellPhone: Locator;
  readonly assignConcept: Locator;
  readonly conceptNameInp: Locator;
  readonly ordersToAssignOctChk: Locator;
  readonly schoolCicloInp: Locator;
  readonly inactiveStudentStatus: Locator;
  readonly activeStudentStatus: Locator;
  readonly guardianAssignementHead: Locator;
  readonly assignBtn: Locator;
  readonly assingSchollarshipSuccessMsg: Locator;
  readonly cancelBtn: Locator;
  readonly midDelinquencyStudensCounterTxt: Locator;
  readonly lowDelinquencyStudensCounterTxt: Locator;
  readonly studentDetailsHead: Locator;
  readonly specialOverchargeAmountInp: Locator;
  readonly specialOverchargeMotiveInp: Locator;
  readonly specialOverchargeAddBtn: Locator;
  readonly specialOverchargeCloseBtn: Locator;
  readonly monthlyChk: Locator;
  readonly schoolCycleBtn: Locator;
  readonly schoolCycleTodosOpt: Locator;
  readonly optionKinder: Locator;
  readonly optionElementary: Locator;
  readonly rowLevelKinder: Locator;
  readonly rowLevelElementary: Locator;
  readonly levelSelector: Locator;
  readonly cycleSelector: Locator;
  readonly groupSelector: Locator;
  readonly continueBtn: any;
  readonly studentParentRelationSelector: Locator;
  readonly sectionFilterTxtBox: Locator;

  constructor(page: Page) {
    this.page = page;
    this.sectionFilterTxtBox = page.getByTestId('inputText');
    this.studentsTxt = page.getByRole('heading', { name: 'Estudiantes' }).nth(0);
    this.totalStudentsTxt = page.getByText('Total Estudiantes');
    this.totalWithoutDebtStudentsTxt = page.getByText('Estudiantes sin deuda');
    this.totalWithDebtStudentsTxt = page.getByText('Estudiantes morosos');
    this.highDelinquencyTxt = page.getByText('Morosidad Alta');
    this.highDelinquencyHelperTxt = page.getByText('3 o más colegiaturas vencidas sin pagar').nth(0);
    this.mediumDelinquencyTxt = page.getByText('Morosidad Media');
    this.mediumDelinquencyHelperTxt = page.getByText('2 colegiaturas vencidas sin pagar').first();
    this.lowDelinquencyTxt = page.getByText('Morosidad Baja');
    this.lowDelinquencyHelperTxt = page.getByText('1 colegiatura vencida sin pagar').first();
    this.studentsListTxt = page.getByText('Lista de estudiantes');
    this.newStudentBtn = page.getByRole('button', { name: 'Nuevo estudiante' });
    this.studenRowNameTxt = page.getByRole('cell', { name: 'Estudiantes' });
    this.guardinFilterTxtBox = page.getByPlaceholder('Buscar por tutor');
    this.studentFilterTxtBox = page.getByPlaceholder('Buscar por alumno/matricula');
    this.downloadArrowBtn = page.locator('.bg-transparent').first();
    this.goToPageTxtLabel = page.getByText('Ir a la página:');
    this.spinButtonBox = page.getByRole('spinbutton');
    this.navigateOnePageBtn = page.getByRole('button').nth(12);
    this.xOfx = page.getByTestId('pageCounterTxt-span');
    this.navigateLastPageBtn = page.locator('button:nth-child(4)');
    this.lastPageCount = page.getByText('22 de 22');
    this.navigateFirstPageBtn = page.locator('.sticky > div > button').first();
    this.firstPageCount = page.getByText('1 de 22');
    this.studentLevel = page.getByText('Secundaria');
    this.levelFilterSelector = page.getByRole('button', { name: 'Nivel' });
    this.optionSecundaria = page.getByLabel('Secundaria');
    this.optionPrimaria = page.getByTestId('Primaria-filterOption');
    this.optionKinder = page.getByLabel('Kinder').first();
    this.optionElementary = page.getByLabel('Elementary').first();
    this.optionPreescolar = page.getByRole('option', { name: 'Preescolar' });
    this.rowLevelPreescolar = page.getByRole('cell', { name: 'Preescolar' });
    this.rowLevelSecundaria = page.getByRole('cell', { name: 'Secundaria' });
    this.rowLevelPrimaria = page.getByLabel('Primaria');
    this.rowLevelKinder = page.getByRole('cell', { name: 'Kinder' });
    this.rowLevelElementary = page.getByRole('cell', { name: 'Elementary' });
    this.sectionFilterSelector = page.getByRole('button', { name: 'Sección' });
    this.optionSecciónPrimariaA = page.getByLabel('Primer año APrimaria');
    this.rowSeccionPrimariaA = page.getByRole('cell', { name: 'Primer año A' });
    this.colegiturasVencidasFilterSelector = page.getByRole('button', { name: 'Colegiaturas vencidas' });
    this.optionCV1 = page.getByLabel('1');
    this.optionCV2 = page.getByLabel('2');
    this.optionCV3 = page.getByLabel('3 o más');
    this.tutorFilterTxt = page.getByPlaceholder('Buscar por tutor');
    this.studentFilterTxt = page.getByPlaceholder('Buscar por alumno/matricula');
    this.optionFilteredByTutor = page.getByRole('option', { name: 'Gabriel Nicora Email: gabriel@getcometa.com' });
    this.optionFilteredByStudent = page.getByRole('heading', { name: 'pablo perez' });
    this.filterBtn = page.getByRole('button', { name: 'Filtrar' });
    this.applyFilterBtn = page.getByRole('button', { name: 'Aplicar' });
    this.cleanAllFiltersBtn = page.getByRole('button', { name: 'Limpiar todo' });
    this.highDelinquencyStudensCounterTxt = page.getByTestId('highDelinquencyStudensCounter-text');
    this.midDelinquencyStudensCounterTxt = page.getByTestId('midDelinquencyStudensCounter-text');
    this.lowDelinquencyStudensCounterTxt = page.getByTestId('lowDelinquencyStudensCounter-text');
    this.schoollarshipCicle = page.getByLabel('Ciclo escolar');
    this.delinquencyStatics = page.getByRole('main').locator('div').filter({ hasText: 'Morosidad Alta' }).nth(3);
    this.studentFirstName = page.locator('input[name="first_name"]');
    this.studentLastName = page.locator('input[name="last_name"]');
    this.studentCurp = page.locator('input[name="identifier"]');
    this.studentBirthdate = page.locator('input[name="birthdate"]');
    this.genderM = page.getByLabel('Masculino');
    this.nextBtn = page.getByRole('button', { name: 'Siguiente' });
    this.enrollmentCode = page.locator('input[name="enrollment_code"]');
    this.levelDD = page.getByText('NivelNivel');
    this.gradeBtn = page.locator('button').filter({ hasText: 'Grado' });
    this.groupBtn = page.locator('button').filter({ hasText: 'Grupo' });
    this.findExistingGuardianChk = page.getByLabel('Buscar un tutor existente');
    this.registerNewGuardianChk = page.getByTestId('createGuardianRadio');
    this.guardianFirstName = page.locator('input[name="firstName"]');
    this.guardianLastName = page.locator('input[name="lastName"]');
    this.guardianEmail = page.locator('input[name="email"]');
    this.guardianCellPhone = page.getByTestId('phone-input');
    this.assignConcept = page.getByRole('button', { name: 'Asignar concepto' });
    this.conceptNameInp = page.getByPlaceholder('Selecciona un concepto');
    this.ordersToAssignOctChk = page.locator('xpath=//span[text()="diciembre 2023"]');
    this.monthlyChk = page.getByTestId('generic-checkbox');
    this.schoolCicloInp = page.getByPlaceholder('Ciclo escolar');
    this.inactiveStudentStatus = page.getByText('Inactivo');
    this.activeStudentStatus = page.getByText('Activo');
    this.guardianAssignementHead = page.getByRole('heading', { name: 'Tutores asignados' });
    this.assignBtn = page.getByRole('button', { name: 'Asignar' });
    this.assingSchollarshipSuccessMsg = page.getByText('¡Se asignó la beca correctamente!');
    this.cancelBtn = page.getByRole('button', { name: 'Cancelar' });
    this.studentDetailsHead = page.getByTestId('studentDetail-header');
    this.specialOverchargeAmountInp = page.getByTestId('price-input');
    this.specialOverchargeMotiveInp = page.getByTestId('specialOverchargeMotive-input');
    this.specialOverchargeAddBtn = page.getByTestId('add-button');
    this.specialOverchargeCloseBtn = page.getByTestId('close-button');
    this.schoolCycleBtn = page.getByTestId('schoolCycle-combobox');
    this.schoolCycleTodosOpt = page.getByRole('option', { name: 'Todos' });
    this.cycleSelector = page.getByLabel('Nivel');
    this.levelSelector = page.getByText('NivelNivel');
    this.groupSelector = page.getByText('GrupoGrupo');
    this.continueBtn = page.getByRole('button', { name: 'Continuar' });
    this.studentParentRelationSelector = page.getByTestId('Parentesco con el estudiante');
  }
}
