export const AUTH_ERRORS = {
  REFRESH_ACCESS_TOKEN_ERROR: 'RefreshAccessTokenError',
} as const;

export const AUTH_CONFIG = {
  TOKEN_EXPIRY_OFFSET_SECONDS: 20,
  DEFAULT_ACCESS_TOKEN_EXPIRY_SECONDS: 60,
  DEFAULT_REFRESH_TOKEN_EXPIRY_SECONDS: 7 * 24 * 60 * 60,
  SESSION_DURATION_WITHOUT_REMEMBER_SECONDS: 8 * 60 * 60,
} as const;
