/**
 * @deprecated: Do not use this enum use `TrackEvents` instead
 */
export enum Events {
  // Backend events
  bulk_concept_assignment_failure = 'Back: Bulk Concept Assignment (Failure)',
  bulk_concept_assignment_success = 'Back: Bulk Concept Assignment (Success)',
  bulk_scholarship_assignment_failure = 'Back: Bulk Scholarship Assignment (Failure)',
  bulk_scholarship_assignment_started = 'Back: Bulk Scholarship Assignment (Started)',
  concept_created = 'Back: Concept Created',
  concept_failed = 'Back: Concept Failed',
  concept_single_order_created = 'Back: Concept Single Order Created',
  concept_with_attributes_created = 'Back: Concept With Attributes Created',
  // Concept events
  concept_assigned = 'dashboard: Concept | Assigned',
  concept_assignment_cancelled = 'dashboard: Concept | Assignment cancelled',
  concept_click_assign = 'dashboard: Concept | Clicked assign',
  concept_click_assignment = 'dashboard: Concept | Clicked assignment',
  concept_click_cancel = 'dashboard: Concept | Clicked cancel',
  concept_click_edit_orders = 'dashboard: Concept | Click edit orders',
  concept_click_month_charged = 'dashboard: Concept | Clicked month to be charged',
  concept_click_drop_month_charged = 'dashboard: Concept | Clicked drop month to be charged',
  concept_click_unassign = 'dashboard: Concept | Click Unassign',
  concept_detail = 'dashboard: Concept Detail Opened',
  concept_detail_viewed = 'dashboard: Concept | Detail viewed',
  concept_edited = 'dashboard: Concept | Edited',
  concept_error_assigning = 'dashboard: Concept | Error when assigning',
  concept_new_p2a1_meses = 'dashboard: Concept | New Concept P2A.1.1 Meses',
  concept_new_p2a1_single_order = 'dashboard: Concept | New Concept P2A.1.2 Single Order',
  concept_new_p2a2_recargos = 'dashboard: Concept | New Concept P2A.2 Recargos',
  concept_new_p2a3_descuentos = 'dashboard: Concept | New Concept P2A.3 Descuentos',
  concept_new_p2b1_atributos = 'dashboard: Concept | New Concept P2B.1 Atributos',
  concept_new_p2b2_ordenes = 'dashboard: Concept | New Concept P2B.2 Ordenes',
  concept_new_started = 'Dashboard - New concept Started',
  concept_unassigned = 'dashboard: Concept | Unassigned',
  //Concept creation events
  concept_creation_step_1_information = 'dashboard: Concept | New Concept P1 - Complete',
  concept_creation_step_2_months = 'dashboard: Concept | New Concept P2A.1.1 Meses - Complete',
  concept_creation_step_3_interest = 'dashboard: Concept | New Concept P2A.2 Recargos - Complete',
  concept_creation_step_4_discount = 'dashboard: Concept | New Concept P2A.3 Descuentos - Complete',
  concept_creation_step_5_invoce = 'dashboard: Concept | New Concept P3 Facturacion - Complete',
  concept_creation_step_6_attributes_creation = 'dashboard: Concept | New Concept P2B.1 Atributos - Complete',
  concept_creation_step_7_orders_creation = 'dashboard: Concept | New Concept P2B.2 Ordenes - Complete',
  concept_creation_step_8_single_order = 'dashboard: Concept | New Concept P2A.1.2 Single Order - Complete',
  // Delinquency events // TODO: Remove these after the legacy delinquency page is removed
  delinquency_downloaded = 'dashboard: Delinquency Downloaded',
  delinquency_order_open = 'dashboard: delinquency order open',
  delinquency_student_detail_close = 'dashboard: delinquency student detail close',
  delinquency_student_detail_open = 'dashboard: delinquency student detail open',
  // Payments events
  deposits_downloaded = 'dashboard: Deposits Downloaded',
  direct_payment_detail_opened = 'dashboard: Direct Payment Detail Opened',
  direct_payments_downloaded = 'dashboard: Direct Payments Downloaded',
  download_students_list_report = 'dashboard: Students Table Downloaded',
  filtro_pagos_recibidos = 'dashboard: Filtro Pagos Recibidos',
  outstanding_orders = 'dashboard: Outstanding Orders Detail Opened',
  outstanding_orders_downloaded = 'dashboard: Outstanding Orders Downloaded',
  paid_orders_downloaded = 'dashboard: Paid Orders Downloaded',
  paid_orders_detail_opened = 'dashboard: Paid Order Detail Opened',
  pagos_recibidos_downloaded = 'dashboard: Pagos Recibidos Downloaded',
  pagos_recibidos_downloaded_lower = 'dashboard: Pagos recibidos Downloaded',
  pagos_recibidos_order_open = 'dashboard: Pagos Recibidos order open',
  // Manual payments events
  manual_pay_discount_deleted = 'dashboard: Manual Payment Discount Deleted',
  manual_pay_discount_deleted_error = 'dashboard: Manual Payment Discount Deleted Error',
  manual_payment_initiated = 'dashboard: Manual Payment Initiated',
  manual_payment_order_detail_opened = 'dashboard: Manual Payment Order Detail Opened',
  manual_payment_orders_selected = 'dashboard: Manual Payment Orders Selected',
  manual_payment_add_interest_forget = 'dashboard: Manual Payment Add Interest Forget',
  manual_payment_error_add_interest_forget = 'dashboard: Manual Payment Error Add Interest Forget',
  manual_discount_initiated = 'dashboard: Manual Discount Initiated',
  fulfillment_price_edit_error = 'dashboard: Fulfillment price edit error',
  edit_fulfillment_price_canceled = 'dashboard: Edit fulfillment price canceled',
  manual_payment_discount_canceled = 'dashboard: Manual Payment Discount Canceled',
  manual_payment_guardian_selected = 'dashboard: Manual Payment Guardian Selected',
  manual_payment_student_selected = 'dashboard: Manual Payment Student Selected',
  // Received payments events
  payin_detail_payment_deleted = 'dashboard: Payin Detail | Payment Deleted',
  payins_report_downloaded = 'dashboard: Payins | Report Downloaded',
  // Deposits events
  payouts_detail_opened = 'dashboard: Deposits Detail Opened',
  payouts_report_downloaded = 'dashboard: Deposits Downloaded',
  // Partial payments events
  partial_payment_edited = 'dashboard: Partial Payment Edited',
  // Authentication events
  auth_login = 'dashboard: Authentication | Login',
  auth_reset_password = 'dashboard: Authentication | Reset Password Requested',
  // Navigation events
  navigation_configuration = 'dashboard: Navigation | Configuration',
  navigation_logout = 'dashboard: Navigation | Logout',
  // Guardians events
  guardian_changed = 'dashboard: Guardian | Changed',
  guardian_click_send_wa = 'dashboard: Guardian | Click Send WA',
  guardian_detail_viewed = 'dashboard: Guardian | Detail viewed',
  guardian_mail_notifications_off = 'dashboard: Guardian | Mail Notifications off',
  guardian_unassign_student = 'dashboard: Guardian | Unassign student',
  guardian_wa_notifications_off = 'dashboard: Guardian | WA Notifications off',
  // Scholarships events
  scholarship_assigned = 'dashboard: Scolarship | Assigned',
  scholarship_cancelled = 'dashboard: Scolarship | Cancelled',
  scholarship_click_assign = 'dashboard: Scolarship | Clicked assign',
  scholarship_click_assignment = 'dashboard: Scolarship | Clicked assignment',
  scholarship_click_cancel = 'dashboard: Scolarship | Clicked cancel',
  scholarship_click_unassign = 'dashboard: Scolarship | Click Unassign',
  scholarship_detail_viewed = 'dashboard: Scolarship | Detail viewed',
  scholarship_error_assigning = 'dashboard: Scolarship | Error when assigning',
  scholarship_unassigned = 'dashboard: Scolarship | Unassigned',
  // Invoices events
  invoices_view_guardian = 'dashboard: Invoices | View Guardian',
  // Grades and levels events
  grade_edit_click_cancel = 'dashboard: Grade edit | Clicked cancel',
  level_edit_click_cancel = 'dashboard: Level edit | Clicked cancel',
  // Collections Events
  eficiencia_cobranzas_downloaded = 'dashboard: Eficiencia de Cobranzas Downloaded',
  // School Cycle Events
  school_cycle_activate_error = 'dashboard:school_cycle:change_cycle:activate:error',
  school_cycle_activate = 'dashboard:school_cycle:change_cycle:activate',
  // General events
  new_student_started = 'dashboard: New Student Started',
  student_detail_opened = 'dashboard: Student Detail Opened',
  support_requested = 'dashboard: Support Requested',
  multiple_filters_applied = 'dashboard: Multiple Filters | Applied',
}

export const PageViewedCategory = 'Dashboard';

export const TrackEvents = {
  concepts: {
    duplicateStarted: 'dashboard: Concept | Duplicate | Started',
    duplicateSuccess: 'dashboard: Concept | Duplicate | Success',
    duplicateFailed: 'dashboard: Concept | Duplicate | Failed',
  },
  performance: {
    pageLoadTime: 'Page Load Time',
  },
  announcements: {
    pageViewedSent: 'Home - Dashboard Comunicaciones - Comunicados Enviados',
    pageViewedDraft: 'Home - Dashboard Comunicaciones - Comunicados Borradores',
    pageViewedPending: 'Home - Dashboard Comunicaciones - Comunicados Programados',
    sentTabClicked: 'dashboard: Sent Announcements Nav Clicked',
    draftTabClicked: 'dashboard: Draft Announcements Nav Clicked',
    pendingTabClicked: 'dashboard: Programmed Announcements Nav Clicked',
    createAnnouncementClicked: 'dashboard: Announcements Create Clicked',
    pageViewedNewAnnouncement: 'Home - Dashboard Comunicaciones - Crea tu Contenido',
    addCoverClicked: 'dashboard: Announcements Add Cover Clicked',
    editTitleClicked: 'dashboard: Announcements Edit Title Clicked',
    editBodyClicked: 'dashboard: Announcements Edit Body Clicked',
    boldTextClicked: 'dashboard: Announcements Rich Text Bold Clicked',
    italicTextClicked: 'dashboard: Announcements Rich Text Italic Clicked',
    emojiClicked: 'dashboard: Announcements Rich Text Emoji Clicked',
    leftTextClicked: 'dashboard: Announcements Rich Text Left Clicked',
    centerTextClicked: 'dashboard: Announcements Rich Text Center Clicked',
    rightTextClicked: 'dashboard: Announcements Rich Text Right Clicked',
    aiIntentionClicked: 'dashboard: Announcements AI Intention Clicked',
    aiIntentionClosed: 'dashboard: Announcements AI Intention Closed',
    aiOptionSubmitted: 'dashboard: Announcements AI Option Submitted',
    questionStatementClicked: 'dashboard: Announcements Question Statement Clicked',
    questionStatementEdited: 'dashboard: Announcements Question Statement Edited',
    responseTypeSelected: 'dashboard: Announcements Response Type Selected',
    optionFieldClicked: 'dashboard: Announcements Option Field Clicked',
    questionResponseTypeSelected: 'dashboard: Question Response Type Selected',
    questionOptionFieldClicked: 'dashboard: Question Option Field Clicked',
    questionOptionEdited: 'dashboard: Question Option Edited',
    questionOptionAddClicked: 'dashboard: Question Option Add Clicked',
    questionAddClicked: 'dashboard: Question Add Clicked',
    questionBuilderViewed: 'dashboard: Question Builder Viewed',
    formFileUploaded: 'dashboard: Form File Uploaded',
    stepNextClicked: 'dashboard: Announcements Step Next Clicked',
    audienceSelectorViewed: 'dashboard: Audience Selector Viewed',
    audienceSearchUsed: 'dashboard: Audience Search Used',
    audienceGroupExpanded: 'dashboard: Audience Group Expanded',
    audienceGroupSelected: 'dashboard: Audience Group Selected',
    audienceGroupDeselected: 'dashboard: Audience Group Deselected',
    audienceSubgroupExpanded: 'dashboard: Audience Subgroup Expanded',
    audienceStudentSelected: 'dashboard: Audience Student Selected',
    audienceStudentDeselected: 'dashboard: Audience Student Deselected',
    audienceSchoolYearChanged: 'dashboard: Audience SchoolYear Changed',
    audiencePreviewClicked: 'dashboard: Audience Preview Clicked',
    configSendNowSelected: 'dashboard: Config Send Now Selected',
    configScheduleSelected: 'dashboard: Config Schedule Selected',
    configSendDateSet: 'dashboard: Config Send Date Set',
    configRequiredResponseEnabled: 'dashboard: Config Required Response Enabled',
    configRequiredResponseDisabled: 'dashboard: Config Required Response Disabled',
    configMaxResponseDateEnabled: 'dashboard: Config Max Response Date Enabled',
    configMaxResponseDateDisabled: 'dashboard: Config Max Response Date Disabled',
    configMaxResponseDateSet: 'dashboard: Config Max Response Date Set',
    stepperBackClicked: 'dashboard: Stepper Back Clicked',
    saveDraftModalShown: 'dashboard: Save Draft Modal Shown',
    saveDraftModalNoClicked: 'dashboard: Save Draft Modal No Clicked',
    saveDraftModalYesClicked: 'dashboard: Save Draft Modal Yes Clicked',
    saveDraftModalClosed: 'dashboard: Save Draft Modal Closed',
    announcementSendClicked: 'dashboard: Announcement Send Clicked',
    detail: {
      pageViewed: 'Home - Dashboard Comunicaciones - Detalle Comunicado',
      announcementDetailsSelected: 'dashboard: Announcement Detalis Selected',
      announcementDetailTabClicked: 'dashboard: Announcement Detail Tab Clicked',
      announcementEditClicked: 'dashboard: Announcement Edit Clicked',
      announcementDeleteClicked: 'dashboard: Announcement Delete Clicked',
      announcementDeleteConfirmed: 'dashboard: Announcement Delete Confirmed',
      announcementBackClicked: 'dashboard: Announcement Back Clicked',
      announcementRecipientExpanded: 'dashboard: Announcement Recipient Expanded',
      announcementRecipientCollapsed: 'dashboard: Announcement Recipient Collapsed',
      announcementRecipientsReportDownloaded: 'dashboard: Announcement Recipients Report Downloaded',
      recipientsFilterClicked: 'dashboard: Recipients Filter Clicked',
      recipientsFilterApplied: 'dashboard: Recipients Filter Applied',
      recipientsSearchUsed: 'dashboard: Recipients Search Used',
      responsesReportDownloaded: 'dashboard: Responses Report Downloaded',
      responsesFilterClicked: 'dashboard: Responses Filter Clicked',
      responsesFilterApplied: 'dashboard: Responses Filter Applied',
      responsesSearchUsed: 'dashboard: Responses Search Used',
    },
  },
  institution: {
    updated: 'dashboard: Institution Data Updated',
  },
  onboarding: {
    pageViewed: 'Home - Dashboard Configuración Inicial',
  },
  invoicing: {
    configurationUpdated: 'dashboard: Invoicing Configuration Updated',
    configurationUpdateFailed: 'dashboard: Invoicing Configuration Update Failed',
    historyClicked: 'dashboard: Invoicing | History Clicked',
  },
  paymentBlock: {
    historyClicked: 'dashboard: Payment Block | History Clicked',
    createBlockStarted: 'dashboard: Payment Block | Create Block Started',
    createBlockConfirmed: 'dashboard: Payment Block | Create Block Confirmed',
    deleteBlockStarted: 'dashboard: Payment Block | Delete Block Started',
    deleteBlockConfirmed: 'dashboard: Payment Block | Delete Block Confirmed',
  },
  scholarships: {
    configurationUpdated: 'dashboard: Scholarships Configuration Updated',
    configurationUpdateFailed: 'dashboard: Scholarships Configuration Update Failed',
    createStarted: 'dashboard: Scholarship | Create | Started',
    createSuccess: 'dashboard: Scholarship | Create | Success',
    createFailed: 'dashboard: Scholarship | Create | Failed',
  },
  manualPayments: {
    created: 'dashboard: ManualPay Create',
    failed: 'dashboard: Manual Payment Failed',
  },
  delinquency: {
    delinquency_downloaded: 'dashboard: Delinquency Downloaded',
    delinquency_order_open: 'dashboard: delinquency order open',
    delinquency_student_detail_close: 'dashboard: delinquency student detail close',
    delinquency_student_detail_open: 'dashboard: delinquency student detail open',
  },
  attendance: {
    flowStarted: 'dashboard: Attendance | Flow Started',
    modeSelected: 'dashboard: Attendance | Mode Selected',
    aiRecordingStarted: 'dashboard: Attendance | AI Recording Started',
    aiRecordingFailed: 'dashboard: Attendance | AI Recording Failed',
    aiResultShown: 'dashboard: Attendance | AI Result Shown',
    submitClicked: 'dashboard: Attendance | Submit Clicked',
    flowExited: 'dashboard: Attendance | Flow Exited',
  },
};
