export const SCHOOL_CYCLE_CONSTANTS = {
  INSCRIPTION_TOTAL_MONTHS: 20,
  REGULAR_CONCEPT_TOTAL_MONTHS: 13,
  REGULAR_CONCEPT_TOTAL_MONTHS_WITH_END: 14,
  INSCRIPTION_START_MONTH: 0,
  REGULAR_START_MONTH: 7,
  DEFAULT_SCHOOL_YEAR: 2000,
} as const;
